### ISSUE TITLE
本地运行ok了，怎么部署线上呢？

### ISSUE THREAD

**Issue by zc-boy** [lscho/thinkjs_model_demo#1]
我本地运行好了，弄不懂怎么部署线上，望指教 ^-^

**Comment by lscho** [comment]
不好意思，刚看到，部署线上可以使用Docker 或者 pm2，参考[https://thinkjs.org/zh-cn/doc/3.0/deploy.html](https://thinkjs.org/zh-cn/doc/3.0/deploy.html)
